package github.ricemonger.telegramBot.executors;

public enum InputState {
    BASE,
    CREDENTIALS_FULL_OR_EMAIL,
    CREDENTIALS_PASSWORD,
    ACTIVE_CREDENTIALS,
    FILTER_NAME,
    FILTER_TYPE,
    FILTER_IS_OWNED,
    FILTER_ITEM_NAME_PATTERNS,
    FILTER_ITEM_TYPES,
    FILTER_ITEM_TAGS_RARITY,
    FILTER_ITEM_TAGS_SEASONS,
    FILTER_ITEM_TAGS_OPERATORS,
    FILTER_ITEM_TAGS_WEAPONS,
    FILTER_ITEM_TAGS_EVENTS,
    FILTER_ITEM_TAGS_ESPORTS,
    FILTER_ITEM_TAGS_OTHER,
    FILTER_MIN_PRICE,
    FILTER_MAX_PRICE,
    FILTER_MIN_LAST_SOLD_PRICE,
    FILTER_MAX_LAST_SOLD_PRICE,
    FILTER_LAST_SOLD_DATE,
    ITEM_OFFSET
}
