package github.ricemonger.telegramBot.executors;

public enum InputGroup {
    BASE,
    CREDENTIALS_ADD,
    CREDENTIALS_REMOVE_ONE,
    FILTERS_EDIT,
    FILTERS_SHOW_REMOVE,
    ITEMS_SHOW_SETTINGS_CHANGE_MESSAGE_LIMIT,
    ITEMS_SHOW_SETTING_CHANGE_SHOWN_FIELDS,
    ITEMS_SHOW_SETTING_APPLIED_FILTERS_CHANGE, ITEM_SHOW
}
