mutation CreateSellOrder($spaceId: String!, $tradeItems: [TradeOrderItem!]!, $paymentOptions: [PaymentItem!]!) {
    createSellOrder(
        spaceId: $spaceId
        tradeItems: $tradeItems
        paymentOptions: $paymentOptions
    ) {
        trade {
            __typename
        }
        __typename
    }
}