query GetTradesLimitations($spaceId: String!) {
    game(spaceId: $spaceId) {
        viewer {
            meta {
                tradesLimitations {
                    ...TradesLimitationsFragment
                    __typename
                }
                __typename
            }
            __typename
        }
        __typename
    }
}

fragment TradesLimitationsFragment on UserGameTradesLimitations {
    buy {
        resolvedTransactionCount
        activeTransactionCount
        __typename
    }
    sell {
        resolvedTransactionCount
        activeTransactionCount
        resaleLocks {
            itemId
            expiresAt
            __typename
        }
        __typename
    }
    __typename
}



