mutation CreateBuyOrder($spaceId: String!, $tradeItems: [TradeOrderItem!]!, $paymentProposal: PaymentItem!) {
    createBuyOrder(
        spaceId: $spaceId
        tradeItems: $tradeItems
        paymentProposal: $paymentProposal
    ) {
        trade {
            __typename
        }
        __typename
    }
}