mutation UpdateSellOrder($spaceId: String!, $tradeId: String!, $paymentOptions: [PaymentItem!]!) {
    updateSellOrder(
        spaceId: $spaceId
        tradeId: $tradeId
        paymentOptions: $paymentOptions
    ) {
        trade {
            __typename
        }
        __typename
    }
}