query GetTransactionsPending($spaceId: String!, $limit: Int!, $offset: Int) {
    game(spaceId: $spaceId) {
        viewer {
            meta {
                trades(
                    limit: $limit
                    offset: $offset
                    filterBy: {states: [Created]}
                    sortBy: {field: LAST_MODIFIED_AT}
                ) {
                    nodes {
                        ...TradeFragment
                        __typename
                    }
                    __typename
                }
                __typename
            }
            __typename
        }
        __typename
    }
}

fragment TradeFragment on Trade {
    tradeId
    state
    category
    expiresAt
    lastModifiedAt
    tradeItems {
        item {
            ...SecondaryStoreItemFragment
            __typename
        }
        __typename
    }
    paymentOptions {
        price
        transactionFee
        __typename
    }
    paymentProposal {
        price
        __typename
    }
    __typename
}

fragment SecondaryStoreItemFragment on SecondaryStoreItem {
    itemId
    __typename
}
