mutation UpdateBuyOrder($spaceId: String!, $tradeId: String!, $paymentProposal: PaymentItem!) {
    updateBuyOrder(
        spaceId: $spaceId
        tradeId: $tradeId
        paymentProposal: $paymentProposal
    ) {
        trade {
            __typename
        }
        __typename
    }
}