query GetItemDetails($spaceId: String!, $itemId: String!) {
    game(spaceId: $spaceId) {
        marketableItem(itemId: $itemId) {
            item {
                ...SecondaryStoreItemFragment
                ...SecondaryStoreItemOwnershipFragment
                __typename
            }
            marketData {
                ...MarketDataFragment
                __typename
            }
            paymentLimitations {
                minPrice
                maxPrice
                __typename
            }
            __typename
        }
        viewer {
            meta {
                id
                trades(filterBy: {states: [Created], itemIds: [$itemId]}) {
                    nodes {
                        ...TradeFragment
                        __typename
                    }
                    __typename
                }
                __typename
            }
            __typename
        }
        __typename
    }
}

fragment SecondaryStoreItemFragment on SecondaryStoreItem {
    id
    assetUrl
    name
    tags
    type
    viewer {
        meta {
            isReserved
            __typename
        }
        __typename
    }
    __typename
}

fragment SecondaryStoreItemOwnershipFragment on SecondaryStoreItem {
    viewer {
        meta {
            isOwned
            __typename
        }
        __typename
    }
    __typename
}

fragment MarketDataFragment on MarketableItemMarketData {
    sellStats {
        lowestPrice
        activeCount
        __typename
    }
    buyStats {
        highestPrice
        activeCount
        __typename
    }
    lastSoldAt {
        price
        performedAt
        __typename
    }
    __typename
}

fragment TradeFragment on Trade {
    tradeId
    state
    category
    expiresAt
    lastModifiedAt
    payment {
        price
        transactionFee
        __typename
    }
    paymentOptions {
        price
        transactionFee
        __typename
    }
    paymentProposal {
        price
        __typename
    }
    __typename
}

