query GetSellableItems($spaceId: String!, $limit: Int!, $offset: Int, $sortBy: MarketableItemSort) {
    game(spaceId: $spaceId) {
        viewer {
            meta {
                marketableItems(
                    limit: $limit
                    offset: $offset
                    sortBy: $sortBy
                ) {
                    nodes {
                        ...MarketableItemFragment
                        __typename
                    }
                    totalCount
                    __typename
                }
                __typename
            }
            __typename
        }
        __typename
    }
}

fragment MarketableItemFragment on MarketableItem {
    item {
        ...SecondaryStoreItemFragment
        __typename
    }
    __typename
}

fragment SecondaryStoreItemFragment on SecondaryStoreItem {
    id
    __typename
}