package github.ricemonger.telegramBot;

public enum InputGroup {
    BASE,
    UBI_ACCOUNT_ENTRY_LINK,
    ITEM_FILTER_EDIT,
    ITEM_FILTER_SHOW_OR_REMOVE,
    ITEMS_SHOW_SETTINGS_CHANGE_MESSAGE_LIMIT,
    ITEMS_SHOW_SETTING_CHANGE_SHOWN_FIELDS,
    ITEMS_SHOW_SETTING_CHANGE_APPLIED_FILTERS,
    ITEMS_SHOW,
    TRADE_BY_ITEM_ID_MANAGER_TYPE_BUY_EDIT,
    TRADE_BY_ITEM_ID_MANAGER_TYPE_SELL_EDIT,
    TRADE_BY_ITEM_ID_MANAGER_TYPE_BUY_AND_SELL_EDIT,
    TRADE_BY_FILTERS_MANAGER_EDIT,
    TRADE_BY_ITEM_ID_MANAGER_SHOW_OR_REMOVE,
    TRADE_BY_FILTERS_MANAGER_SHOW_OR_REMOVE,
    UBI_ACCOUNT_ENTRY_REAUTHORIZE_2FA_CODE
}
