package github.ricemonger.telegramBot;

public enum InputGroup {
    BASE,
    CREDENTIALS_ADD,
    CREDENTIALS_REMOVE_ONE,
    FILTERS_EDIT,
    FILTERS_SHOW_REMOVE,
    ITEMS_SHOW_SETTINGS_CHANGE_MESSAGE_LIMIT,
    ITEMS_SHOW_SETTING_CHANGE_SHOWN_FIELDS,
    ITEMS_SHOW_SETTING_APPLIED_FILTERS_CHANGE,
    ITEM_SHOW,
    TRADES_EDIT_ONE_ITEM_BUY,
    TRADES_EDIT_ONE_ITEM_SELL,
    TRADES_EDIT_ONE_ITEM_BUY_AND_SELL,
    TRADES_EDIT_ITEM_FILTER,
    TRADES_REMOVE_ITEM_ID,
    TRADES_REMOVE_ITEM_FILTERS
}
